//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nte.erp.services.invoices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nte.erp.services.invoices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;cac:InvoiceLine&gt;
        ///    &lt;cbc:ID&gt;{LineID}&lt;/cbc:ID&gt;
        ///    &lt;cbc:InvoicedQuantity unitCode=&quot;H87&quot;&gt;{InvoiceQuantiy}&lt;/cbc:InvoicedQuantity&gt;
        ///    &lt;cbc:LineExtensionAmount currencyID=&quot;RSD&quot;&gt;{PriceAmount}&lt;/cbc:LineExtensionAmount&gt;
        ///    &lt;cac:Item&gt;
        ///      &lt;cbc:Name&gt;{ItemName}&lt;/cbc:Name&gt;
        ///      &lt;cac:ClassifiedTaxCategory&gt;
        ///        &lt;cbc:ID&gt;{TaxCategotyID}&lt;/cbc:ID&gt;
        ///        &lt;cbc:Percent&gt;{ClasifiedPercentTax}&lt;/cbc:Percent&gt;
        ///        &lt;cac:TaxScheme&gt;
        ///          &lt;cbc:ID&gt;VAT&lt;/cbc:ID&gt;
        ///        &lt;/cac:TaxScheme&gt;
        ///      &lt;/cac:Classi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateItems {
            get {
                return ResourceManager.GetString("TemplateItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Invoice xmlns:cec=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2&quot; xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2&quot; xmlns:cbc=&quot;urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:sbt=&quot;http://mfin.gov.rs/srbdt/srbdtext&quot; xmlns=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateMain {
            get {
                return ResourceManager.GetString("TemplateMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;cac:TaxSubtotal&gt;
        ///      &lt;cbc:TaxableAmount currencyID=&quot;RSD&quot;&gt;{TaxSubTotaltaxableAmount}&lt;/cbc:TaxableAmount&gt;
        ///      &lt;cbc:TaxAmount currencyID=&quot;RSD&quot;&gt;{TaxSubTotalAmount}&lt;/cbc:TaxAmount&gt;
        ///      &lt;cac:TaxCategory&gt;
        ///        &lt;cbc:ID&gt;{TaxCategotyID}&lt;/cbc:ID&gt;
        ///        &lt;cbc:Percent&gt;0&lt;/cbc:Percent&gt;
        ///        &lt;cbc:TaxExemptionReasonCode&gt;{TaxExemptionReason}&lt;/cbc:TaxExemptionReasonCode&gt;
        ///        &lt;cac:TaxScheme&gt;
        ///          &lt;cbc:ID&gt;VAT&lt;/cbc:ID&gt;
        ///        &lt;/cac:TaxScheme&gt;
        ///      &lt;/cac:TaxCategory&gt;
        ///    &lt;/cac:TaxSubtotal&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateTaxes {
            get {
                return ResourceManager.GetString("TemplateTaxes", resourceCulture);
            }
        }
    }
}
